looping_talker:
  ros__parameters:
    qos_overrides:
      '/looping_message':
        publisher:
          reliability: reliable
          history: keep_last
          depth: 10000


event_driven_listener:
  ros__parameters:
    qos_overrides:
      '/looping_message':
        subscription:
          reliability: reliable
          history: keep_last
          depth: 10000

timer_driven_listener:
  ros__parameters:
    qos_overrides:
      '/looping_message':
        subscription:
          reliability: reliable
          history: keep_last
          depth: 10000


busy_looping_listener:
  ros__parameters:
    qos_overrides:
      '/looping_message':
        subscription:
          reliability: reliable
          history: keep_last
          depth: 10000
